### ISSUE TITLE
Option to display files in ZIP order

### ISSUE THREAD

**Issue by bart-d** [16colo-rs/16c#22]
This'd put file separators where they were intended to be.

(originally entered by nail)

**Comment by andyherbert** [comment]
This is my no.1 complaint of the site atm. It has nothing to do with separators though. I like flicking through the pack by pressing right and left, but never know for sure which file to start with. Having previews is nice but I would like a vertical list, similar to Pablo, where you can see the filenames in 'pack order'.

**Comment by bart-d** [comment]
imho Pablodraw sorts alphabetically and not in order the order in the zip archive. However if you press right in the pack overview you ll automatically start with the first file.

Where would such a filelist be placed in the UI?

**Comment by andyherbert** [comment]
By pack order, I mean alphabetically, in other words all the artists should be grouped together and if there's any filenames starting with '_' then they've been shifted to the top. I didn't know about right arrow key in the main view, so I'll start using that. I imagine the file list would work similar to Pablo, on the left hand side, but whatever works I guess.

**Comment by bart-d** [comment]
option to display files in archive order was implemented earlier and is available from the view menu.
