### ISSUE TITLE
search by artwork size (eg length)

### ISSUE THREAD

**Issue by bart-d** [16colo-rs/16c#28]
(originally requested by giulio)

**Comment by bart-d** [comment]
lordscarlet: is number of lines being stored anywhere right now?

**Comment by bart-d** [comment]
> 
> 
> lordscarlet: is number of lines being stored anywhere right now?

yes, in statitem (meta.db)

**Comment by lordscarlet** [comment]
@bart-d my `statitem` is empty -- how does it get populated? I haven't found any code yet that does anything but `select` from it.

**Update:** looks like it is `file-stats.php`, which only pulls information from tagged items. But my `tagitems` is empty. Going to take this offline to discuss then bring the results back here.

**Comment by lordscarlet** [comment]
@bart-d looks like its `file-stats.php`? Investigating..

**Comment by bart-d** [comment]
Off the top of my head it's populated when an item gets tagged. Can't look at the code right now :)

**Comment by bart-d** [comment]
Could be that file-stats is run from from and only selects tagged items
