### ISSUE TITLE
in-pack Ajax search does not work on mobile

### ISSUE THREAD

**Issue by bart-d** [16colo-rs/16c#3]

**Comment by lordscarlet** [comment]
What aspect of this doesn't work? If I use the Chrome Dev Tools emulator, and I remove the class that hides the search on mobile, the functionality works. Is this an instance where the emulator doesn't show a true picture, or am I missing something? (clearly it needs some slightly different styles on mobile)

![image](https://user-images.githubusercontent.com/17951/82448277-7f8db300-9a77-11ea-91b5-0b67b111c515.png)

**Comment by bart-d** [comment]
i noticed this myself on Android (Chrome and FF). i think it's related to the search being triggered on keyup, maybe those events don't exist or behave differently on mobile.

**Comment by bart-d** [comment]
i tried this again, on a mobile device and it works. but the searchbox takes up so much space, i'm considering to leave it hidden on mobile.

**Comment by lordscarlet** [comment]
Yeah, its a bit of a ui problem as far as that goes. You could probably position or size it a little better, but its always going to be fairly large. You could perhaps cause it to open a modal on mobile? Not sure the right answer. Someone can also use the mobile browser _Find in page_ functionality.

**Comment by bart-d** [comment]
indeed, i'm going to put it to rest for now :)
