### ISSUE TITLE
Make textmode artwork content indexed by search engines

### ISSUE THREAD

**Issue by lordscarlet** [16colo-rs/16c#38]
It could be tough to work around [Google guidelines](https://support.google.com/webmasters/answer/66353?hl=en), but I don't think it would be against the spirit of the guidelines. 

Very possibly related to #33.

**Comment by lordscarlet** [comment]
I am wondering if doing #52 would help with this?

**Comment by bart-d** [comment]
I'm not really sure which structured data fits this purpose and also the length of the content. per piece i have between 0 and 100.000 characters. it was up to 2 million but i did some cleaning in the FTS index last week. obviously those which are really long we can trim somewhat but still for example infofiles i'd like to have them indexed completely and they can contain a lot of text.

i've been looking at this isues earlier and I want to be very careful with hidden content to prevent punishment. https://support.google.com/webmasters/answer/66353?hl=en

i was also considering to raise the question in /r/TechSEO

**Comment by lordscarlet** [comment]
Yeah. That's why I was wondering about using structured data. That does not seem to violate the "hidden content" situation especially if we use `JSON-LD`. I think [CreativeWork](https://schema.org/CreativeWork) would certainly apply in this situation. What I don't know is that it would actually put the `description` as something that gets picked up by search.

**Comment by bart-d** [comment]
extracted text is now available under the image (after clicking a button)
