### ISSUE TITLE
Allow users to mark favorites

### ISSUE THREAD

**Issue by lordscarlet** [16colo-rs/16c#41]
<3

**Comment by christianvozar** [comment]
Not only do I 👍 on this but I'd love to see it extended into a list system where I could share a list of ansis. I could see Misfit creating lists with themes and sharing the list to social media.

I'm not ignorant to how much work that would be, a ton, but it's a cool idea all the same.

**Comment by bart-d** [comment]
added in https://github.com/16colo-rs/16colo.rs/commit/e6f9df2136e2c2259cd653685cb83ea45c5d79e5
