### ISSUE TITLE
Group statistics page

### ISSUE THREAD

**Issue by bart-d** [16colo-rs/16c#49]
Much like the /artist pages, we also need  /group pages with group statistics.

Which details/numbers could be useful/interesting to show?

**Comment by lordscarlet** [comment]
**Mimic from Artists**
years active (number of packs)
lifetime artworks
lifetime lines
first/last release

**Unique to a pack**
artists
years active (number of artists)
lifetime artists
lifetime packs

**Comment by bart-d** [comment]
ideas picked up from the drunk warpus brainstorm ;)

- graphical timeline (members and/or packs)
- top contributing member
- longest serving member
- blender points
- ~~number of merges with iCE~~
- "aggregate graph"
- single group artists
- average time between pack releases
- average ansi length
- member/guest release %
- average packs size in terms on # of ansis
- biggest pack/smallest pack
- pack with best rated arrt
- best rated ansi
- % of ansis in pack vs othert art forms
- top 5 artists by some algorithms that considers # of releases and avg rating
- most productive artists
- number of ansis released by artist (searchbox), graph of contributions
- degrees of separation (artist page)

**Comment by christianvozar** [comment]
Just chiming in this sounds awesome. 👍
