### ISSUE TITLE
return to original page after login

### ISSUE THREAD

**Issue by bart-d** [16colo-rs/16c#57]
some editors would like to be redirected to the page where they logged in from. this involves moving the editor info page somewhere else.

**Comment by lordscarlet** [comment]
By that do you mean that the editor info page is not currently linked from anywhere?

**Comment by bart-d** [comment]
indeed the page with some documentation for editors is the login page itself. it's only seen right after login. or if you click "login" when already logged in. quite likely there is a better place. but initially i wanted to push the information in their face, because quite a few of them still don't know the editor functions despite all the information. also because of the most of the editor functions that are somewhat hidden. 

but here the issue is that someone is on a certain page, wants to eg tag and is not logged in. in that case they want to go back to where they were...

**Comment by bart-d** [comment]
https://github.com/16colo-rs/16colo.rs/commit/e6f9df2136e2c2259cd653685cb83ea45c5d79e5 has modified a account page including a new (blue) button which will redirect back to the original page right before authentication
