### ISSUE TITLE
Filename extension listed as '.'

### ISSUE THREAD

**Issue by andyherbert** [16colo-rs/16c#59]
On the mis0520 page on the extension list there's an option for just '.'. Selecting this option does not appear to apply any filter.

<img width="202" alt="Screenshot 2020-05-26 at 06 53 10" src="https://user-images.githubusercontent.com/25620/82865033-c408cb00-9f1d-11ea-805b-2ad4bc085ad6.png">

**Comment by bart-d** [comment]
fixed in https://github.com/16colo-rs/16colo.rs/commit/62d1c39d7b0459f9cde0d244d8b752150d3b95c1
