### ISSUE TITLE
Links included in the file included somewhere on the page

### ISSUE THREAD

**Issue by andyherbert** [16colo-rs/16c#64]
For example, for https://16colo.rs/pack/mist0620/US-SOLOSCROLL.ANS the link at the bottom of the piece is clickable somewhere.

**Comment by bart-d** [comment]
a test version with extracted text and clickable links is currently available by changing 'pack' into 'pack2' in the URL, eg: 
https://16colo.rs/pack2/mist0620/US-SOLOSCROLL.ANS

**Comment by bart-d** [comment]
extracted text and hyperlinks are now available below the image (after clicking a button)
