### ISSUE TITLE
Warn Uploader of Missing `file_id.diz`

### ISSUE THREAD

**Issue by christianvozar** [16colo-rs/16c#66]
There are more releases, not from days past but current, that are being released with no file_id.diz. Take Null 09 for instance and I know for a fact the uploader has a file_id.diz as they used it in past releases. Perhaps a sanity check before publishing a pack with a warning to the uploader "No file_id.diz was found and the thumbnail will be blank, are you ok with this?"

**Comment by bart-d** [comment]
null009 has a FILE_ID.DIZ: https://16colo.rs/mag/null009/

this is a new issues introduced after making it possible to move packs to the emag section. the latest section is just not taking into account a DIZ in the mag section, so this is where the real issue is

**Comment by bart-d** [comment]
fixed in https://github.com/16colo-rs/16colo.rs/commit/335847e89356ba643bc46d5e1132a260d039183c
