### ISSUE TITLE
Advertisements Counted Against Tag Completion/Stats for Packs

### ISSUE THREAD

**Issue by christianvozar** [16colo-rs/16c#72]
Take Odium 05 for example, https://16colo.rs/pack/odium-05

There are multiple nocturnal desire adverts that were inserted into the pack's .zip. I understand it is impractical to remove them (the adverts) but perhaps the https://16colo.rs/stats.php?t=tagsa could ignore any content tag with an `advert` tag so I can assume a pack is fully tagged. I really do not want to have to tag adverts with artists and such (there will be a LOT of dups) just to finish off a pack. But happily will tag the adverts so they can be ignored as I pass them.

**Comment by bart-d** [comment]
if you hide those files (through the editor menu or the quick menu) those files won't be counted for tag completion. the hide feature is there to remove clutter files such as ads and seperators from the default view.

**Comment by christianvozar** [comment]
Awesome, didn't know that was the purpose of that function but adverts
watch out! I'm coming for you.
