### ISSUE TITLE
Allow Artist Pages to Specify Designated Logo like Group Page

### ISSUE THREAD

**Issue by christianvozar** [16colo-rs/16c#73]
Love the specified group logo idea, wondered if it could be applied to artist pages.

**Comment by bart-d** [comment]
not really sure what you intend with a 'logo', i know its common lately to draw eachothers nickname in ANSI, but i doubt this is available for the bulk that was active in the nineties.

In any case, there is already a 'reference' image selected per artist, it's just not very visible on the site. But when you share on social media, this image will be shown in the preview. if you look at the source of the artist page and search for "og:image" you'll find the URL to that 'reference' image.

the selection is done automatically, it's based on either rating or in case of not enough ratings, the most recent image. but maybe that is not what you've imagined it would be?

**Comment by christianvozar** [comment]
My thought was pretty simple: I was editing a group page and thought this would be cool to do for an artist. (being able to add a defined image, even from PASTE, and a social media like like Instagram.)

That said it would be tedious and likely not very fruitful to implement this for artists when I think about it. Having the best rated ansi art for an artist appear as the social image preview makes a lot of sense to me. Could that also be the piece that is displayed largely next to the artist name on the artist page (similar to how the group logo is shown?

**Comment by bart-d** [comment]
> Could that also be the piece that is displayed largely next to the artist name on the artist page (similar to how the group logo is shown?

technically it could be displayed. but the height could be very different, it could be an extremely long scroller or a 80x25 screen. so it'll be hard to fit in the layout properly.
