### ISSUE TITLE
animated GIFs and their thumbnails

### ISSUE THREAD

**Issue by NicheInterests** [16colo-rs/16c#82]
Dealing with GIF animation is ahistorical in an artpack context, and yet I keep irritatingly inviting new kinds of computer art into artpacks through the Trojan horse that is Mistigris.  Mostly 16c handles them just fine more or less, but often their preview thumbnails at the "artpack at a glance" level are glitchy.

Also:

"https://16colo.rs/pack/mist1117/FREDDY43-LOGOPRINTER.GIF specifically is a case where full size display through 16c is jumbled...
2017/mist1117/FREDDY43-LOGOPRINTER.GIF - Logoprinter by Freddy43 an...
mistigris - Logoprinter by Freddy43 and Dead So

Even though the raw file at https://16colo.rs/pack/mist1117/raw/FREDDY43-LOGOPRINTER.GIF looks perfect in the same browser!"

**Comment by bart-d** [comment]
resolved in https://github.com/16colo-rs/16colo.rs/commit/1a57a2d0420b1ca5c8a0153c350d4d813f6e20d4

these seem to be edge cases, as I've only found 3 GIF's with glitches after rescaling. the fix requires existing images to be reconverted, if there are any left with issues, please post them here.
