### ISSUE TITLE
ANSImation enabled with use of other (Amiga) fonts

### ISSUE THREAD

**Issue by NicheInterests** [16colo-rs/16c#83]
CT: Dwimmer sent me the frames of https://16colo.rs/pack/5i1m4110207st1/DWIMMER-GUIDANCE.GIF as ansi files and I tried to use TheDraw to composite them together to deliver an authentically ansimated version, but (expired link) is as close as I got, and... it's a vicious mockery.  I'm curious ... why even after overriding the display font in the pack editor I can't force use of the desired Amiga characters.  (Except in the "output scroller" video generator, which sadly just scrolls the final frame only in the desired font.)  Any ideas?

Burps: it would be the very first time i've ever seen an ansimation in an Amiga font and thus the output in another font than CP437 is currently not supported. I would need to add that (which is possible as ansilove-js supports some amiga fonts)

**Comment by bart-d** [comment]
resolved in https://github.com/16colo-rs/16colo.rs/commit/21c9e97dafb0b9db866efedf280561a0ad87338a
PC codepages & Amiga font support through SAUCE or 16c render settings

eg: https://16colo.rs/pack/bac-v10/the_ghetto3.txt (not sure of the intended font setting but it appears like Amiga-ish)
