### ISSUE TITLE
Incorrect tag link formatting

### ISSUE THREAD

**Issue by andyherbert** [16colo-rs/16c#87]
When clicking on a tag containing a space, the URL uses '+' to replace the space instead of '%20'.

e.g. https://16colo.rs/pack/badapple/FILE_ID.DIZ links to https://16colo.rs/tags/content/ansi+music instead of https://16colo.rs/tags/content/ansi%20music when clicking the 'ansi music' tag.

**Comment by livejamie** [comment]
Confirmed, another example is clicking on "The Knight" in the sauce here: https://16colo.rs/pack/fl-ansi1/TK-JCONF.FL
