### ISSUE TITLE
Support for blinking ANSI art

### ISSUE THREAD

**Issue by andyherbert** [16colo-rs/16c#88]
The recent Fire pack contained a piece by ResetSurvivor which took advantage of blinking text. The site doesn't support blinking text beyond the animation viewer. PNGs support animation, se attached image
![R5-SHRF](https://github.com/user-attachments/assets/52cbdb00-f5e9-4c0e-86a9-a6cb44bcb9e1)

**Comment by bart-d** [comment]
i suggest you'd raise this as an feature request or submit a PR to https://github.com/ansilove/libansilove
in addition to that, i'm not sure it should be done, it's at the very least uncommon for blink to be visible beyond the line limit of a character console.

**Comment by andyherbert** [comment]
ok thanks.
