### ISSUE TITLE
API: sauce=true breaks response sometimes

### ISSUE THREAD

**Issue by michael-lazar** [16colo-rs/16c#93]
This API endpoint returns an empty response:

https://api.16colo.rs/v1/pack/hpm-03?archive=true&content=true&groups=true&artists=true&fileid=true&sauce=true

but it works without the `&sauce=true` at the end:

https://api.16colo.rs/v1/pack/hpm-03?archive=true&content=true&groups=true&artists=true&fileid=true

**Comment by bart-d** [comment]
SAUCE is user input and can thus be invalid, in this case UTF8 characters. i've adjusted to make an attempt to replace UTF8 characters however when extracting SAUCE one should always assume that the input may be invalid.
